[server]
fileWatcherType = "poll"
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#667eea"
backgroundColor = "#0f0c29"
secondaryBackgroundColor = "#302b63"
textColor = "#ffffff"

[runner]
magicEnabled = false
